---

- name: Assert Ansible version
  assert:
    that: ansible_version.full is version('2.8', '>=')

- name: Assert key variables
  assert:
    that:
    - os_auth_url is defined
    - os_auth_url|length > 0

# Deletes our bastion.
#
# On OpenStack this is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' checks that these variables are set.

- name: Delete Bastion?
  pause:
    prompt: |-
      Are you sure you want to delete the '{{ instance_base_name }}' bastion?
      Hit return to delete.
      Hit Ctrl+c and then "a" if you've changed your mind

# No need to detach the volume
# (we see errors if it's not there anyway)
# so just delete the server...

- name: Delete bastion node
  os_server:
    auth: "{{ os_auth }}"
    region_name: "{{ os_region_name }}"
    name: "{{ instance_base_name }}-bastion"
    state: absent
