---

- name: Assert Ansible version
  assert:
    that: ansible_version.full is version('2.8', '>=')

# On OpenStack this is driven by variables that should be defined by
# 'sourcing' your OpenStack Keystone file. The initial
# 'assert' checks that these variables are set.

- name: Assert key variables
  assert:
    that:
    - os_auth_url is defined
    - os_auth_url|length > 0

# Off we go...

- include_tasks: create-{{ provider }}-instances.yaml
- include_tasks: gather-{{ provider }}-facts.yaml
