---

# A convenient authentication dictionary.
# Used by numerous OpenStack tasks.
os_auth:
  auth_url: "{{ os_auth_url }}"
  username: "{{ os_username }}"
  password: "{{ os_password }}"
  project_id: "{{ os_project_id }}"
  user_domain_name: "{{ os_user_domain_name }}"
